'use strict';
const $=id=>document.getElementById(id);
const descriptions=['Addition and subtraction to 12. Times tables and division to 12 × 12.','Add and subtract to 50. Multiplication and division with larger factors.','Add and subtract to 150, negative answers, and multiplication up to 25 × 30.','Percentages, fractions, signed numbers, and order of operations.','Linear equations, functions, and slope. Solve for x when asked.','Quadratics, exponentials, logarithms, polynomials, and rational equations.'];
const targets=[6,9,14,18,25,35];let duration=120,state=null,timer=null,history=[],autoTimer=null,advanceTimer=null;const storageKey='quick-math-v1';
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved))history=saved.filter(r=>r&&Number.isFinite(r.correct)&&Number.isFinite(r.total)&&r.total>=r.correct&&r.correct>=0);}catch(e){}
function historyView(){const el=$('history-content');el.replaceChildren();if(!history.length){el.textContent='Your first round starts here. Small sessions add up.';el.className='small';return;}el.className='history-row';const total=history.reduce((n,r)=>n+r.total,0),correct=history.reduce((n,r)=>n+r.correct,0);for(const [value,label]of[[history.length,'rounds played'],[correct,'answers correct'],[total?Math.round(correct/total*100)+'%':'—','overall accuracy']]){const box=document.createElement('div');box.className='metric';const b=document.createElement('strong');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);el.append(box);}}
function setupLevel(){$('level-help').textContent=descriptions[+$('level').value];$('operation-field').hidden=+$('level').value>=3;historyView();}
$('level').onchange=setupLevel;
$('game-level').innerHTML=$('level').innerHTML;
$('game-operation').innerHTML=$('operation').innerHTML;
function gameSettingsHelp(){$('game-level-help').textContent=descriptions[+$('game-level').value];$('game-operation-field').hidden=+$('game-level').value>=3;}
$('game-level').onchange=gameSettingsHelp;
$('apply-settings').onclick=()=>{const level=$('game-level').value,operation=$('game-operation').value,seconds=+$('game-duration').value;if(state&&!state.done)finish();$('level').value=level;$('operation').value=operation;duration=seconds;document.querySelectorAll('[data-duration]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.duration===duration)));setupLevel();start();};
document.querySelectorAll('[data-duration]').forEach(b=>b.onclick=()=>{duration=+b.dataset.duration;document.querySelectorAll('[data-duration]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
function screen(name){for(const id of ['setup','play','results','progress'])$(id).hidden=id!==name;$('nav-practice').setAttribute('aria-current',name==='progress'?'false':'page');$('nav-progress').setAttribute('aria-current',name==='progress'?'page':'false');window.scrollTo(0,0);}
function elapsed(){return state.elapsed+(state.paused?0:performance.now()-state.tickStart);}
function questionElapsed(){return performance.now()-state.questionStart;}
function start(){clearAuto();if(state&&!state.done&&state.total)saveRound(false);clearInterval(timer);state={id:globalThis.crypto?.randomUUID?.()||String(Date.now())+Math.random(),started:new Date().toISOString(),topics:{},level:+$('level').value,operation:$('operation').value,duration,elapsed:0,tickStart:performance.now(),paused:false,answered:false,correct:0,total:0,streak:0,best:0,times:[],misses:[],done:false};screen('play');$('game-level').value=String(state.level);$('game-operation').value=state.operation;$('game-duration').value=String(duration);gameSettingsHelp();$('round-name').textContent=$('level').selectedOptions[0].textContent;$('active-game').hidden=false;$('paused').hidden=true;$('pause').hidden=false;$('time-label').textContent=duration?'remaining':'practicing';next();timer=setInterval(tick,100);tick();}
function next(){clearAuto();if(!state||state.done||state.paused)return;if(state.duration&&elapsed()>=state.duration*1000){finish();return;}state.q=MathEngine.question(state.level,state.operation);state.questionStart=performance.now();state.answered=false;$('auto-hint').textContent='Correct answers check instantly';$('auto-hint').className='auto-hint';$('question').textContent=state.q.text;$('topic').textContent=state.q.topic;$('answer-form').hidden=false;$('feedback').hidden=true;$('answer').value='';$('input-error').textContent='';$('pace-target').textContent=`Pace guide: ${targets[state.level]} sec / answer`;$('answer').focus();tick();}
function tick(){if(!state||state.done||state.paused)return;const ms=elapsed();if(state.duration&&ms>=state.duration*1000){finish();return;}const sec=state.duration?Math.ceil((state.duration*1000-ms)/1000):Math.floor(ms/1000);$('time').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;$('time-bar').style.transform=`scaleX(${state.duration?Math.max(0,1-ms/(state.duration*1000)):1})`;$('score').textContent=state.correct;$('accuracy').textContent=state.total?Math.round(state.correct/state.total*100)+'%':'—';$('streak').textContent=state.streak;if(!state.answered){const t=questionElapsed()/1000;$('pace-state').textContent=t>targets[state.level]?'Take your time. Accuracy first.':`${t.toFixed(1)} sec`;}}
function submit(skip=false){if(!state||state.done||state.paused||state.answered)return;if(state.duration&&elapsed()>=state.duration*1000){finish();return;}const value=MathEngine.parseAnswer($('answer').value);if(!skip&&value===null){$('input-error').textContent='Enter a number or fraction, such as -3 or 1/2.';return;}clearAuto();state.answered=true;const seconds=questionElapsed()/1000;const correct=!skip&&Math.abs(value-state.q.answer)<1e-8;state.total++;const topic=state.topics[state.q.topic]||(state.topics[state.q.topic]={total:0,correct:0});topic.total++;if(correct)topic.correct++;if(correct){state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);state.times.push(seconds);}else{state.streak=0;state.misses.push({...state.q,given:skip?'Skipped':$('answer').value});}$('answer-form').hidden=true;$('feedback').hidden=false;$('feedback').className=correct?'':'wrong';$('feedback-title').textContent=correct?`Correct · ${seconds.toFixed(1)} seconds`:`${skip?'Skipped':'Not quite'} · Answer: ${state.q.answer}`;$('explanation').textContent=correct?(seconds<=targets[state.level]?'Right on pace. Keep it going.':'Accurate first. Speed comes with practice.'):state.q.explanation;$('pace-state').textContent=`${seconds.toFixed(1)} sec`;saveRound(false);$('next').textContent=correct?'Next question →':'Got it. Next question →';$('next').focus();tick();if(correct&&!state.done)advanceTimer=setTimeout(next,700);}
function pause(){clearAuto();if(!state||state.done||state.paused)return;if(state.duration&&elapsed()>=state.duration*1000){finish();return;}state.elapsed=elapsed();state.pausedAt=performance.now();state.paused=true;$('active-game').hidden=true;$('paused').hidden=false;$('pause').hidden=true;$('resume').focus();}
function resume(){if(!state||!state.paused||state.done)return;state.questionStart+=performance.now()-state.pausedAt;state.tickStart=performance.now();state.paused=false;$('active-game').hidden=false;$('paused').hidden=true;$('pause').hidden=false;(state.answered?$('next'):$('answer')).focus();tick();if(!state.answered&&$('answer').value)queueAnswer();}
function finish(){clearAuto();if(!state||state.done)return;const activeSeconds=Math.min(elapsed()/1000,state.duration||Infinity);state.done=true;clearInterval(timer);screen('results');const accuracy=state.total?Math.round(state.correct/state.total*100):0;const average=state.times.length?state.times.reduce((a,b)=>a+b,0)/state.times.length:null;$('result-correct').textContent=`${state.correct}/${state.total}`;$('result-accuracy').textContent=state.total?accuracy+'%':'—';$('result-speed').textContent=average===null?'—':average.toFixed(1)+'s';$('result-message').textContent=!state.total?'A fresh start is one round away.':accuracy>=90?'Accuracy is looking strong. Keep this pace, or try the next level.':accuracy>=70?'A solid start. Repeat this level and let accuracy lead.':'Slow it down. Try untimed practice and build a reliable rhythm.';$('result-detail').textContent=`${Math.round(activeSeconds)} seconds practiced · Best streak: ${state.best}. Skips count toward accuracy; unfinished questions do not. Average time uses correct answers only.`;if(state.total)saveRound(true);reviewIndex=0;renderReview();$('again').focus();}
$('start').onclick=start;$('again').onclick=start;$('change').onclick=()=>{screen('setup');setupLevel();$('level').focus();};$('answer-form').onsubmit=e=>{e.preventDefault();submit();};$('skip').onclick=()=>submit(true);$('next').onclick=next;$('pause').onclick=pause;$('resume').onclick=resume;$('finish').onclick=finish;
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
for(const key of ['1','2','3','4','5','6','7','8','9','−','0','⌫','.','/','Clear']){const b=document.createElement('button');b.type='button';b.textContent=key;if(['⌫','Clear'].includes(key))b.className='utility';if(key==='⌫')b.setAttribute('aria-label','Delete last digit');b.onclick=()=>{const a=$('answer');if(key==='Clear')a.value='';else if(key==='⌫')a.value=a.value.slice(0,-1);else if(a.value.length<32)a.value+=key==='−'?'-':key;queueAnswer();};document.querySelector('.keypad').append(b);}
setupLevel();

function clearAuto(){clearTimeout(autoTimer);clearTimeout(advanceTimer);}
function queueAnswer(){
 clearTimeout(autoTimer);
 if(!state||state.done||state.paused||state.answered)return;
 $('input-error').textContent='';
 const value=$('answer').value.trim();
 const numeric=MathEngine.parseAnswer(value);
 if(numeric!==null&&Math.abs(numeric-state.q.answer)<1e-8){submit();return;}
 $('auto-hint').textContent=value?'Checking after typing stops…':'Correct answers check instantly';
 $('auto-hint').className=value?'auto-hint typing':'auto-hint';
 if(value)autoTimer=setTimeout(()=>submit(),1100);
}
$('answer').addEventListener('input',queueAnswer);
$('answer').addEventListener('compositionstart',()=>clearTimeout(autoTimer));
$('answer').addEventListener('compositionend',queueAnswer);
$('phone-settings').onclick=()=>{pause();screen('setup');setupLevel();};
$('nav-practice').onclick=()=>{if(state&&!state.done){screen('play');}else{screen('setup');setupLevel();}};
$('nav-progress').onclick=()=>{pause();screen('progress');renderProgress();};
const touchPad=matchMedia('(max-width:700px) and (pointer:coarse)');
function configureInput(){ $('answer').readOnly=touchPad.matches; $('answer').setAttribute('inputmode',touchPad.matches?'none':'decimal'); }
touchPad.addEventListener('change',configureInput);
configureInput();
